### PR TITLE
first patch for reloading the saved targets, read the config file

### PR DESCRIPTION
**Pull request by ls-zhu**
Hi,
I have been working for the feature "reloading the saved targets" for a while, I have posted a thread in the target-devel mail list about this feature. Now I think maybe it is time to push some small patches on this feature, they would be really small patches, better for discussion and correction.

I don't know whether I should push this patch against master branch, but I find the devel branch is quite old, out of date.

I am looking forward for your feedback, hope I can help here!

Thanks

### CODE REVIEW

**Comment by rickysarraf** [comment]
The master branch has hardly had any changes lately. I think it should be
okay to rebase against it.

I'd be interested in looking at your changes.

s3nt fr0m a $martph0ne, excuse typ0s

**Comment by izhu** [comment]
@rickysarraf 
Hi,
Thanks for your help. I find there are only two branches, master and devel, so I should create another pull request against devel branch or waiting for this branch rebase?

Thanks for your help!
BR
Zhu Lingshan

**Comment by rickysarraf** [comment]
On Wed, 2015-10-07 at 08:45 -0700, izhu wrote:
> @rickysarraf 
> Hi,
> Thanks for your help. I find there are only two branches, master and
> devel, so I should create another pull request against devel branch
> or waiting for this branch rebase?
> Thanks for your help!


Hello Zhu,

The branches/repository is owned by Jerome Martin. Looking at the devel
branch, I see nothing recent in it.

You should just base your changes against the master branch.


-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by rickysarraf** [comment]
@izhu BTW, what exactly is missing in the current code ?

Isn't the config already backed up and read in the CliConfig class ?

**Comment by izhu** [comment]
@rickysarraf 

Hi, the config is saved in by the function save_running_config(), but I did not see any functions can reload the saved target in the config file(like after reboot, when we run targetcli again, we want the saved targets reloaded), so I think maybe I can do some contributions for this feature

**Comment by rickysarraf** [comment]
On Wed, 2015-10-14 at 00:56 -0700, izhu wrote:
> Hi, the config is saved in by the function save_running_config(), but
> I did not see any functions can reload the saved target in the config
> file(like after reboot, when we run targetcli again, we want the
> saved targets reloaded), so I think maybe I can do some contributions
> for this feature

From what I see in the code, that is because targetcli is not a daemon
but a set of kernel modules, for which, after its loaded, you need to
have a proper config file written to the configfs.

So, yes. Your patch may make sense. You should also add relevant
changes to the scripts/target.init file.

And maybe have it reviewed with @nablio3000

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by tramjoe** [comment]
Implemented a reload command in configure mode that loads the saved system config and commits it. See http://thread.gmane.org/gmane.linux.scsi.target.devel/10229.

**Comment by ls-zhu** [comment]
@tramjoe 
Hi,

Thanks for your notice and care for this patch!

I got little confused.. The thread in the maillist is posted by me. (Yes, My name is Zhu Linshan, and my company email address is lszhu@suse.com) I just talked about this pull request in the thread. We still not have this feature implemented.

Shall we look through this feature and pull request again? If possible, is it OK to set a updated devel branch for feature development? I found the current devel branch is out of date.

Thanks for your help and efforts@

Thanks,
BR
Zhu Lingshan

**Comment by ls-zhu** [comment]
@tramjoe 

Hi ,
I just see you mail, I think that works for me, thanks for your help!

Thanks,
BR
Zhu Lingshan

**Pull request closed without merging**
